#!/usr/bin/with-contenv bash
# shellcheck shell=bash

SUBJECT="/C=US/ST=CA/L=Carlsbad/O=Linuxserver.io/OU=LSIO Server/CN=*"
if [[ -f /config/keys/pure-ftpd.pem ]]; then
    echo "[init-keygen] using keys found in /config/keys"
else
    echo "[init-keygen] generating self-signed key and certificate in /config/keys/pure-ftpd.pem, you can replace this with your own bundle (key + cert) if required"
    openssl req -new -x509 -days 3650 -nodes -keyout /config/keys/pure-ftpd.pem -out /config/keys/pure-ftpd.pem -subj "$SUBJECT"
fi
