#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ -z "$UPLOADSCRIPT" ]; then
  sleep infinity
fi

if [ ! -f "$UPLOADSCRIPT" ]; then
  echo "[pure-uploadscript] ERROR: File $UPLOADSCRIPT does not exist" >&2
  sleep infinity
fi

echo "[pure-uploadscript] Using script: $UPLOADSCRIPT"

exec pure-uploadscript -p /var/run/pure-uploadscript.pid -r "$UPLOADSCRIPT"
