#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_READ_ONLY_FS} ]]; then
  chmod -R 644 /etc/logrotate.d
fi

if [[ -f "/config/log/logrotate.status" ]]; then
    chmod 600 /config/log/logrotate.status
fi

lsiown -R root:root /config

chmod 0600 \
    /config/keys/pure-ftpd.pem \
    /config/pure-ftpd/pureftpd.passwd \
    /config/pure-ftpd/pureftpd.pdb
